### Random numbers in numpy¶

In [ ]:
# np.random.random()
generates a random number from 0 to 1

In [1]:
import numpy as np

In [2]:
print(np.random.random())

0.2378620427115029


In [3]:
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.4844559791657054
0.7177214474377448
0.10546821330515743
0.04624174323169861


In [4]:
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.36656971322774934
0.5452747613117336
0.09374986303754296
0.0966470668702426


In [6]:
np.random.seed()

In [7]:
np.random.seed(100)
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.5434049417909654
0.27836938509379616
0.4245175907491331
0.8447761323199037


In [8]:
# you can specify the shape
x = np.random.random((4, 4))
x

array([[0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749, 0.97862378],
       [0.81168315, 0.17194101, 0.81622475, 0.27407375]])

### np.random.randint()

In [9]:
num = np.random.randint(low = 20, high =100)
num

79

In [11]:
num = np.random.randint(low = 20, high = 100, size = 5)
num

array([81, 34, 75, 91, 22])

###  np.random.choice(list_of_choice,num_of_ele)

In [12]:
a = [24,27,22,47,35,82,-33,25,2.3,18]
a

[24, 27, 22, 47, 35, 82, -33, 25, 2.3, 18]

In [13]:
np.random.choice(a,size = 3)

array([18., 18., 47.])

In [15]:
np.random.choice(a,size = (5,5))

array([[ 22. ,  82. ,   2.3,  27. ,  24. ],
       [ 25. , -33. ,  22. ,  24. ,   2.3],
       [ 22. ,  82. ,  27. ,   2.3,  27. ],
       [ 82. ,  35. ,  22. ,   2.3,  47. ],
       [ 82. ,  24. ,  18. ,  47. , -33. ]])

###  Other Important functions

In [16]:
x = np.random.random((4, 4))
x

array([[0.97500649, 0.88485329, 0.35950784, 0.59885895],
       [0.35479561, 0.34019022, 0.17808099, 0.23769421],
       [0.04486228, 0.50543143, 0.37625245, 0.5928054 ],
       [0.62994188, 0.14260031, 0.9338413 , 0.94637988]])

####  np.round()

In [ ]:
#rounds an array to given number of decimals

In [17]:
# to round it to 3 decimal points
rounded = np.round(x, 3)
rounded

array([[0.975, 0.885, 0.36 , 0.599],
       [0.355, 0.34 , 0.178, 0.238],
       [0.045, 0.505, 0.376, 0.593],
       [0.63 , 0.143, 0.934, 0.946]])

In [18]:
new = rounded * 100
new

array([[97.5, 88.5, 36. , 59.9],
       [35.5, 34. , 17.8, 23.8],
       [ 4.5, 50.5, 37.6, 59.3],
       [63. , 14.3, 93.4, 94.6]])

### astype()

In [ ]:
#to change the data type of elements

In [19]:
# to change the data type of elements to integers
intt = new.astype(int)
intt

array([[97, 88, 36, 59],
       [35, 34, 17, 23],
       [ 4, 50, 37, 59],
       [63, 14, 93, 94]])

In [20]:
# to change the data type of elements to float
flt = intt.astype(float)
flt

array([[97., 88., 36., 59.],
       [35., 34., 17., 23.],
       [ 4., 50., 37., 59.],
       [63., 14., 93., 94.]])